### ISSUE TITLE
task1: change the main color to green

### ISSUE THREAD

**Issue by phods** [phods/todo_app#1]

**Comment by sighencea** [comment]
When running the command `flutter run` the app can't be built. Error code:

`Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:firebase_core
 - package:firebase_core_platform_interface
 - package:quiver
 - package:plugin_platform_interface
 - package:cloud_firestore
 - package:cloud_firestore_platform_interface

For solutions, see https://dart.dev/go/unsound-null-safety


FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Running Gradle task 'assembleDebug'...                             24.0s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by sighencea** [comment]
Ran on emulator with 'flutter run --no-sound-null-safety'.
Changed the primary and '+' icon colors to green.
Changed 'barrierDismissible' to 'true', to allow for closing the add-task popup when tapping outside of it.
